[colors.bright]
black = "#3e4452"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#be5046"
white = "#5c6370"
yellow = "#d19a66"

[colors.cursor]
cursor = "#528bff"
text = "#0b0b0b"

[colors.footer_bar]
background = "#282c34"
foreground = "#abb2bf"

[colors.normal]
black = "#24272e"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#24272e"
foreground = "#abb2bf"

[colors.search.matches]
background = "#e5c07b"
foreground = "#3e4452"

[colors.selection]
background = "#3e4452"
text = "#abb2bf"

[colors.vi_mode_cursor]
cursor = "#333841"
text = "#abb2bf"

[cursor]
thickness = 0.18
vi_mode_style = "Block"

[font]
size = 11.5

[font.bold]
family = "SauceCodePro NF"
style = "Bold"

[font.italic]
family = "SauceCodePro NF"
style = "Italic"

[font.normal]
family = "SauceCodePro NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Super"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Super"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "U"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "D"
mods = "Super"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "LBracket"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi"

[[keyboard.bindings]]
action = "First"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Last"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control|Alt"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0
