-- luacheck:ignore 631
local u = require('utils')

local codecompanion = require('codecompanion')

local helpers = require('plugin-config.codecompanion.helpers')
local utils = require('codecompanion.utils')
local state_helpers = helpers.state
local chat_helpers = require('codecompanion.interactions.chat.helpers')
local registry = require('codecompanion.interactions.shared.registry')

local picker_helpers = require('plugin-config.codecompanion.pickers.helpers')
local trim_chars = picker_helpers.trim_chars
local pad_right = picker_helpers.pad_right

local M = {}

local ADAPTERS = { 'claude_code', 'codex' }
local PRUNE_INTERVAL = 2 * 60 * 60
local TITLE_WIDTH = picker_helpers.TITLE_WIDTH
local ICONS = {
    current = '\226\151\143', -- ● session open in the current chat
    loaded = '\226\151\139', -- ○ session open in another chat
    clock = '\239\128\151', -- nf-fa-clock_o (U+F017)
}

-- Whole-conversation titles generated by ai_session_title, keyed by
-- `<adapter>:<session_id>`. Read here; refreshed in the background on each browse
local TITLE_CACHE =
    vim.fs.joinpath(vim.fn.stdpath('data'), 'codecompanion', 'acp-session-titles.json')

local function load_title_cache()
    local ok, data = pcall(vim.json.decode, u.read_file(TITLE_CACHE) or '')
    return (ok and type(data) == 'table') and data or {}
end

-- Prune old/single-exchange sessions at most once per 2h, triggered by a
-- browse. Prune is local and quick, so we wait on it before listing
local function ensure_periodic_prune()
    local stamp = vim.fs.joinpath(vim.fn.stdpath('cache'), 'ai_session_prune_stamp')
    local last = tonumber(vim.trim(u.read_file(stamp) or '')) or 0
    if os.time() - last < PRUNE_INTERVAL then
        return
    end

    local result = vim.system({ 'ai_session_prune' }, { text = true }):wait()
    if result.code == 0 then
        local n = tonumber((result.stdout or ''):match('total: deleted (%d+)')) or 0
        if n > 0 then
            utils.notify(
                string.format('Deleted %d session%s', n, n == 1 and '' or 's'),
                vim.log.levels.INFO
            )
        end
    else
        utils.notify('Session prune failed', vim.log.levels.ERROR)
    end

    local fd = io.open(stamp, 'w')
    if fd then
        fd:write(tostring(os.time()))
        fd:close()
    end
end

-- Rough token estimate (~4 chars/token) from the session file size
local function fmt_weight(size)
    local k = (size or 0) / 4 / 1000
    return k >= 1 and string.format('~%.1fk', k) or string.format('~%d', (size or 0) / 4)
end

-- Read up to `max_lines` newline-delimited JSON objects from a file
local function read_jsonl(path, max_lines)
    local out = {}
    local ok, iter = pcall(io.lines, path)
    if not ok then
        return out
    end
    for line in iter do
        local decoded_ok, decoded = pcall(vim.json.decode, line)
        if decoded_ok then
            out[#out + 1] = decoded
        end
        if #out >= max_lines then
            break
        end
    end
    return out
end

local function mtime(path)
    local stat = vim.uv.fs_stat(path)
    return stat and stat.mtime.sec or 0
end

local function clean_title(title)
    return title and vim.trim(title:gsub('%s+', ' ')) or nil
end

local function delete_session(path)
    return vim.uv.fs_unlink(path)
end

local function adapter_label(name)
    return ({ claude_code = 'Claude', codex = 'Codex' })[name] or name
end

-- Map on-disk session ids to the open chat buffer holding them, so the picker
-- can flag which sessions are already live across the open chats
local function open_session_map()
    local map = {}
    for _, entry in ipairs(registry.list()) do
        local chat = codecompanion.buf_get_chat(entry.bufnr)
        local sid = chat and chat.acp_connection and chat.acp_connection.session_id
        if sid then
            map[sid] = entry.bufnr
        end
    end
    return map
end

-- Scan the agents' on-disk session stores. Unlike the ACP `session/list` RPC
-- (which the agent scopes to the request cwd), these discover every session
-- across all working directories, which is what lets us resume from anywhere
local scanners = {}

-- Claude Code stores one <sessionId>.jsonl per session under a per-cwd project
-- dir. The true cwd (needed to load) lives in the message lines. We label from
-- the generated title cache, falling back to the session's native `aiTitle`
scanners.claude_code = function()
    local entries = {}
    local titles = load_title_cache()
    local files =
        vim.fn.glob(vim.fn.expand('~/.claude/projects') .. '/*/*.jsonl', true, true)
    for _, file in ipairs(files) do
        local cwd, ai_title
        for _, d in ipairs(read_jsonl(file, 500)) do
            cwd = cwd or d.cwd
            ai_title = d.aiTitle or ai_title
        end
        if cwd then
            local session_id = vim.fn.fnamemodify(file, ':t:r')
            local cached = titles['claude_code:' .. session_id]
            entries[#entries + 1] = {
                adapter = 'claude_code',
                session_id = session_id,
                cwd = cwd,
                title = clean_title((cached and cached.title) or ai_title),
                updated_at = mtime(file),
                size = (vim.uv.fs_stat(file) or {}).size or 0,
                path = file,
            }
        end
    end
    return entries
end

-- Codex stores date-bucketed rollout-*.jsonl files. The first `session_meta`
-- line holds the id/cwd; the label comes from the title cache
scanners.codex = function()
    local entries = {}
    local titles = load_title_cache()
    local files = vim.fn.glob(
        vim.fn.expand('~/.codex/sessions') .. '/**/rollout-*.jsonl',
        true,
        true
    )
    for _, file in ipairs(files) do
        local meta
        for _, d in ipairs(read_jsonl(file, 50)) do
            if d.type == 'session_meta' then
                meta = d.payload
                break
            end
        end
        if meta and meta.id and meta.cwd then
            local cached = titles['codex:' .. meta.id]
            entries[#entries + 1] = {
                adapter = 'codex',
                session_id = meta.id,
                cwd = meta.cwd,
                title = clean_title(cached and cached.title),
                updated_at = mtime(file),
                size = (vim.uv.fs_stat(file) or {}).size or 0,
                path = file,
            }
        end
    end
    return entries
end

-- Bring up the ACP connection. Only needed to load a session (listing reads
-- disk), so we defer it until after a pick to keep the picker instant and avoid
-- racing the connection setup against the picker opening
local function ensure_connection(chat)
    local handler = require('codecompanion.interactions.chat.acp.handler').new(chat)
    if not handler:ensure_connection() then
        utils.notify('No ACP connection available', vim.log.levels.WARN)
        return false
    end

    if not chat.acp_connection:can_load_session() then
        utils.notify(
            'This ACP adapter does not support loading sessions',
            vim.log.levels.WARN
        )
        return false
    end

    return true
end

-- Build the telescope `display` function (<icon> <title> (~weight)  <clock>
-- <time>  <cwd>), capturing column widths shared by all rows
local function make_display(entries)
    local title_w, provider_w, weight_w, time_w = 0, 0, 0, 0
    for _, e in ipairs(entries) do
        e.display_title = trim_chars(e.title or e.session_id, TITLE_WIDTH)
        e.display_provider = '[' .. adapter_label(e.adapter) .. ']'
        e.display_weight = fmt_weight(e.size)
        e.display_time = e.updated_at and utils.make_relative(e.updated_at) or '?'
        title_w = math.max(title_w, vim.fn.strdisplaywidth(e.display_title))
        provider_w = math.max(provider_w, vim.fn.strdisplaywidth(e.display_provider))
        weight_w = math.max(weight_w, vim.fn.strdisplaywidth(e.display_weight))
        time_w = math.max(time_w, vim.fn.strdisplaywidth(e.display_time))
    end

    return function(picker_entry)
        local e = picker_entry.value
        -- ● current chat's session, ○ loaded in another open chat, blank otherwise
        local marker = e.current and ICONS.current or (e.loaded and ICONS.loaded or ' ')
        local icon = state_helpers.provider_icon(e.adapter)
        local title = pad_right(e.display_title, title_w)
        local provider = pad_right(e.display_provider, provider_w)
        local weight_pad = string.rep(
            ' ',
            math.max(weight_w - vim.fn.strdisplaywidth(e.display_weight), 0)
        )
        local time = pad_right(e.display_time, time_w)
        local cwd = e.cwd and vim.fn.fnamemodify(e.cwd, ':~') or ''
        local meta = string.format(
            '(%s)%s   %s %s',
            e.display_weight,
            weight_pad,
            ICONS.clock,
            time
        )
        local line = string.format(
            '%s %s %s  %s  %s  %s',
            marker,
            icon,
            title,
            provider,
            meta,
            cwd
        )

        local provider_end = #marker + 1 + #icon + 1 + #title + 2 + #provider
        return line, {
            { { provider_end + 1, #line }, 'Comment' },
        }
    end
end

local function load_entry(chat, entry)
    if not ensure_connection(chat) then
        return
    end

    -- The agent locates and roots the session by the cwd passed to session/load,
    -- so switch to the session's original cwd for the duration of the load
    local previous_cwd = vim.fn.getcwd()
    if entry.cwd and vim.fn.isdirectory(entry.cwd) == 1 then
        vim.api.nvim_set_current_dir(entry.cwd)
    end

    local updates = {}
    local ok = chat.acp_connection:load_session(entry.session_id, {
        on_session_update = function(update)
            table.insert(updates, update)
        end,
    })

    if vim.fn.getcwd() ~= previous_cwd and vim.fn.isdirectory(previous_cwd) == 1 then
        vim.api.nvim_set_current_dir(previous_cwd)
    end

    if not ok then
        return utils.notify('Failed to load ACP session', vim.log.levels.ERROR)
    end

    require('codecompanion.interactions.chat.acp.commands').link_buffer_to_session(
        chat.bufnr,
        chat.acp_connection.session_id
    )
    -- Store the loaded session cwd so the chat footer can display it.
    chat.opts.cwd = entry.cwd
    require('codecompanion.interactions.chat.acp.render').restore_session(chat, updates)
    -- Mark the chat as claimed so target_chat won't reuse it for another session
    chat._acp_session_loaded = true

    -- Reuse the session's title for the chat: `opts.title` drives our picker and
    -- the history extension, `set_title` the buffer name/window. Deferred because
    -- restore_session -> chat:clear() triggers the history extension's clear
    -- handler (schedule_wrapped) which nils opts.title; scheduling ours after it
    -- lets our title win. The history extension may later regenerate its own.
    if entry.title and entry.title ~= '' then
        vim.schedule(function()
            if vim.api.nvim_buf_is_valid(chat.bufnr) then
                chat.opts.title = entry.title
                chat:set_title(entry.title)
            end
        end)
    end

    utils.fire('ACPChatRestored', {
        bufnr = chat.bufnr,
        id = chat.id,
        session_id = chat.acp_connection.session_id,
        title = chat.title,
    })
end

local function target_chat(chat, entry)
    local reusable = chat
        and chat.adapter
        and chat.adapter.name == entry.adapter
        and not chat._acp_session_loaded
        and (
            (chat.cycle or 1) <= 1
            or not chat_helpers.has_user_messages(chat.messages or {})
        )

    if reusable then
        return chat
    end

    local previous_cwd = vim.fn.getcwd()
    if entry.cwd and vim.fn.isdirectory(entry.cwd) == 1 then
        vim.api.nvim_set_current_dir(entry.cwd)
    end

    local new_chat = require('codecompanion').chat({
        params = { adapter = entry.adapter },
        auto_submit = false,
    })

    if vim.fn.getcwd() ~= previous_cwd and vim.fn.isdirectory(previous_cwd) == 1 then
        vim.api.nvim_set_current_dir(previous_cwd)
    end

    if not new_chat then
        utils.notify(
            'Failed to create ' .. adapter_label(entry.adapter) .. ' chat',
            vim.log.levels.ERROR
        )
    end

    return new_chat
end

-- `chat` is the optional reuse target (nil when browsing from outside a chat);
-- target_chat spawns a right-adapter chat for the pick when it can't be reused
function M.browse(chat)
    ensure_periodic_prune()

    local entries = {}
    for _, name in ipairs(ADAPTERS) do
        local scan = scanners[name]
        if scan then
            vim.list_extend(entries, scan())
        end
    end

    table.sort(entries, function(a, b)
        return (a.updated_at or 0) > (b.updated_at or 0)
    end)

    if #entries == 0 then
        return utils.notify('No ACP sessions found', vim.log.levels.INFO)
    end

    -- Flag sessions already open in a chat so the picker can mark them
    local open_map = open_session_map()
    local current_sid = chat and chat.acp_connection and chat.acp_connection.session_id
    for _, e in ipairs(entries) do
        e.loaded = open_map[e.session_id] ~= nil
        e.current = e.session_id == current_sid
    end

    -- Telescope picker so we can attach a delete action; <CR> resumes,
    -- d/<A-d> deletes the selected session and refreshes the list
    local pickers = require('telescope.pickers')
    local finders = require('telescope.finders')
    local conf = require('telescope.config').values
    local actions = require('telescope.actions')
    local action_state = require('telescope.actions.state')

    local function make_finder()
        local display = make_display(entries)
        return finders.new_table({
            results = entries,
            entry_maker = function(e)
                return {
                    value = e,
                    display = display,
                    ordinal = adapter_label(e.adapter)
                        .. ' '
                        .. (e.title or '')
                        .. ' '
                        .. (e.cwd or ''),
                }
            end,
        })
    end

    -- Forward-declared so the attach_mappings and refresh closures below can
    -- reference the picker handle (not in scope inside its own initializer)
    local picker
    picker = pickers.new({}, {
        prompt_title = string.format(
            'ACP Sessions (%s current %s loaded | <A-d>:delete)',
            ICONS.current,
            ICONS.loaded
        ),
        finder = make_finder(),
        sorter = conf.generic_sorter({}),
        attach_mappings = function(prompt_bufnr, map)
            -- Resumed picker; the upvalue's results_win is a closed window
            local current = action_state.get_current_picker(prompt_bufnr)
            local selection_hl =
                vim.api.nvim_get_hl(0, { name = 'TelescopeSelection', link = false })
            selection_hl.bold = true
            vim.api.nvim_set_hl(0, 'CodeCompanionSessionSelection', selection_hl)
            vim.wo[current.results_win].winhighlight = table.concat(
                vim.tbl_filter(function(part)
                    return part ~= ''
                end, {
                    vim.wo[current.results_win].winhighlight,
                    'TelescopeSelection:CodeCompanionSessionSelection',
                }),
                ','
            )

            actions.select_default:replace(function()
                local sel = action_state.get_selected_entry()
                actions.close(prompt_bufnr)
                if sel then
                    local selected_chat = target_chat(chat, sel.value)
                    if selected_chat then
                        load_entry(selected_chat, sel.value)
                    end
                end
            end)

            local function delete()
                local targets = current:get_multi_selection()
                if #targets == 0 then
                    targets = { action_state.get_selected_entry() }
                end

                local deleted = {}
                for _, sel in ipairs(targets) do
                    if sel and delete_session(sel.value.path) then
                        deleted[sel.value] = true
                    end
                end

                for i = #entries, 1, -1 do
                    if deleted[entries[i]] then
                        table.remove(entries, i)
                    end
                end
                current:refresh(make_finder(), { reset_prompt = false })

                local n = vim.tbl_count(deleted)
                utils.notify(
                    string.format('Deleted %d session%s', n, n == 1 and '' or 's'),
                    n > 0 and vim.log.levels.INFO or vim.log.levels.WARN
                )
            end

            map('n', 'd', delete)
            map('i', '<A-d>', delete)
            return true
        end,
    })
    picker:find()

    -- Refresh titles for changed sessions in the background so the picker opens
    -- instantly, then patch the open picker in place if any title actually moved
    vim.system({ 'ai_session_title' }, { text = true }, function(obj)
        if tonumber((obj.stdout or ''):match('generated (%d+)')) == 0 then
            return
        end
        vim.schedule(function()
            if
                not picker.prompt_bufnr
                or not vim.api.nvim_buf_is_valid(picker.prompt_bufnr)
            then
                return
            end
            local titles = load_title_cache()
            for _, e in ipairs(entries) do
                local cached = titles[e.adapter .. ':' .. e.session_id]
                if cached and cached.title then
                    e.title = clean_title(cached.title)
                end
            end
            pcall(function()
                picker:refresh(make_finder(), { reset_prompt = false })
            end)
        end)
    end)
end

return M
