#!/bin/sh
. /etc/rc.common

# Note in order for this to work we need to place this file in
# /Library/StartupItems/Synergy and give the proper permissions:
# sudo chmod -R 755 /Library/StartupItems/Synergy/Synergy
# sudo chown -R root:wheel /Library/StartupItems
# sudo chmod -R 755 /Library/StartupItems

# First find ip of server
server_ip=`smbutil lookup pedro-acer|grep response |awk '{print $4}'`

# Start Synergy unless another instance is currently running
run=(/Applications/Synergy.app/Contents/MacOS/synergyc -n pedro-macbook -1 -f $server_ip)

KeepAlive ()
{
    proc=${1##*/}

    while [ -x "$1" ]
    do
        if ! ps axco command | grep -q "^${proc}\$"
        then
           "$@"
        fi

        sleep 3
    done
}

StartService ()
{
    ConsoleMessage "Starting Synergy"
    KeepAlive "${run[@]}" &
}

StopService ()
{
    return 0
}

RestartService ()
{
    return 0
}

RunService "$1"
