#!/usr/bin/env bash
set -euo pipefail

device='tpacpi::kbd_backlight'
level=$(brightnessctl --device="$device" get)
maximum=$(brightnessctl --device="$device" max)
level=$(((level + 1) % (maximum + 1)))
brightnessctl --device="$device" set "$level" > /dev/null
notify-send -i notification-keyboard-brightness 'Keyboard Backlight Change' \
    "New Level: $level"
