keep-open=yes  # Keep window open after video ends
background=color
background-color='#24272e'
hwdec=auto # enable hardware video acceleration
vo=gpu-next # libplacebo renderer

[extension.gif]
loop-file=inf
