---
theme:
  active: "208, 208, 208"   # current song playing
  banner: Green
  error_border: Red
  error_text: Yellow
  hint: Yellow
  hovered: Cyan   # hovered pane border
  inactive: White  # inactive pane border
  playbar_background: Black
  playbar_progress: Green  # progress bar
  playbar_progress_text: "170, 177, 190"
  playbar_text: "170, 177, 190"
  selected: Green
  text: "170, 177, 190"
  header: White  # header in text (Title, Album, etc)

behavior:
  seek_milliseconds: 5000
  volume_increment: 5
  tick_rate_milliseconds: 50

keybindings:
  back: "q"
  increase_volume: "="
...
