general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(24272e)
}

input-field {
    monitor =
    size = 200, 200
    outline_thickness = 3
    rounding = -1
    inner_color = rgb(24272e)
    outer_color = rgb(24272e)
    font_color = rgb(abb2bf)
    check_color = rgb(528bff)
    check_text = Validating
    fail_color = rgb(e06c75)
    fail_text = Wrong!
    placeholder_text =
    dots_size = 0.15
    dots_spacing = 0.15
    dots_center = true
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M:%S"
    color = rgb(abb2bf)
    font_size = 32
    position = 0, 35
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a %b %d"
    color = rgb(abb2bf)
    font_size = 16
    position = 0, -35
    halign = center
    valign = center
}
