background = 0xFF24272E
base = 0xFF2C323C
alternate_base = 0xFF3E4452
text = 0xFFABB2BF
bright_text = 0xFFE5C07B
accent = 0xFF61AFEF
accent_secondary = 0xFFC678DD
icon_theme = Papirus-Dark
font_family = Noto Sans
font_family_monospace = Noto Sans Mono
