general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(24272e)
    blur_passes = 2
}

input-field {
    monitor =
    size = 300, 52
    outline_thickness = 2
    outer_color = rgb(61afef)
    inner_color = rgb(282c34)
    font_color = rgb(abb2bf)
    placeholder_text = Password
    position = 0, -30
    halign = center
    valign = center
}
