local u = require('utils')

local helpers = require('plugin-config.codecompanion.helpers')
local utils = require('codecompanion.utils')
local state_helpers = helpers.state

local M = {}

local TITLE_WIDTH = 80
local PRUNE_INTERVAL = 6 * 60 * 60

-- Whole-conversation titles generated by ai_session_title, keyed by
-- `<adapter>:<session_id>`. Read here; refreshed in the background on each browse
local TITLE_CACHE =
    vim.fs.joinpath(vim.fn.stdpath('data'), 'codecompanion', 'acp-session-titles.json')

local function load_title_cache()
    local ok, data = pcall(vim.json.decode, u.read_file(TITLE_CACHE) or '')
    return (ok and type(data) == 'table') and data or {}
end

-- Prune old/single-exchange sessions at most once per 6h, triggered by a
-- browse. Prune is local and quick, so we wait on it before listing
local function ensure_periodic_prune()
    local stamp = vim.fs.joinpath(vim.fn.stdpath('cache'), 'ai_session_prune_stamp')
    local last = tonumber(vim.trim(u.read_file(stamp) or '')) or 0
    if os.time() - last < PRUNE_INTERVAL then
        return
    end

    utils.notify('Running ACP session prune...', vim.log.levels.INFO)
    local result = vim.system({ 'ai_session_prune' }, { text = true }):wait()
    if result.code == 0 then
        local n = tonumber((result.stdout or ''):match('total: deleted (%d+)')) or 0
        utils.notify(
            string.format('Deleted %d session%s', n, n == 1 and '' or 's'),
            vim.log.levels.INFO
        )
    else
        utils.notify('Session prune failed', vim.log.levels.ERROR)
    end

    local fd = io.open(stamp, 'w')
    if fd then
        fd:write(tostring(os.time()))
        fd:close()
    end
end

-- Rough token estimate (~4 chars/token) from the session file size
local function fmt_weight(size)
    local k = (size or 0) / 4 / 1000
    return k >= 1 and string.format('~%.1fk', k) or string.format('~%d', (size or 0) / 4)
end

-- Read up to `max_lines` newline-delimited JSON objects from a file
local function read_jsonl(path, max_lines)
    local out = {}
    local ok, iter = pcall(io.lines, path)
    if not ok then
        return out
    end
    for line in iter do
        local decoded_ok, decoded = pcall(vim.json.decode, line)
        if decoded_ok then
            out[#out + 1] = decoded
        end
        if #out >= max_lines then
            break
        end
    end
    return out
end

local function mtime(path)
    local stat = vim.uv.fs_stat(path)
    return stat and stat.mtime.sec or 0
end

local function clean_title(title)
    return title and vim.trim(title:gsub('%s+', ' ')) or nil
end

local function trim_chars(text, width)
    text = vim.trim((text or ''):gsub('%s+', ' '))
    if vim.fn.strdisplaywidth(text) <= width then
        return text
    end

    local suffix = '...'
    local limit = width - vim.fn.strdisplaywidth(suffix)
    local out = {}
    local current_width = 0

    for i = 0, vim.fn.strchars(text) - 1 do
        local char = vim.fn.strcharpart(text, i, 1)
        local char_width = vim.fn.strdisplaywidth(char)
        if current_width + char_width > limit then
            break
        end
        out[#out + 1] = char
        current_width = current_width + char_width
    end

    return table.concat(out) .. suffix
end

local function pad_right(text, width)
    return text .. string.rep(' ', math.max(width - vim.fn.strdisplaywidth(text), 0))
end

local function prepare_display(entries)
    local title_width, weight_width, time_width = 0, 0, 0

    for _, e in ipairs(entries) do
        e.display_icon = state_helpers.provider_icon(e.adapter)
        e.display_title = trim_chars(e.title or e.session_id, TITLE_WIDTH)
        e.display_weight = fmt_weight(e.size)
        e.display_time = e.updated_at and utils.make_relative(e.updated_at) or '?'
        e.display_cwd = e.cwd and vim.fn.fnamemodify(e.cwd, ':~') or ''

        title_width = math.max(title_width, vim.fn.strdisplaywidth(e.display_title))
        weight_width = math.max(weight_width, vim.fn.strdisplaywidth(e.display_weight))
        time_width = math.max(time_width, vim.fn.strdisplaywidth(e.display_time))
    end

    for _, e in ipairs(entries) do
        e.display_title_width = title_width
        e.display_weight_width = weight_width
        e.display_time_width = time_width
    end
end

local function delete_session(path)
    return vim.uv.fs_unlink(path)
end

-- Scan the agents' on-disk session stores. Unlike the ACP `session/list` RPC
-- (which the agent scopes to the request cwd), these discover every session
-- across all working directories, which is what lets us resume from anywhere
local scanners = {}

-- Claude Code stores one <sessionId>.jsonl per session under a per-cwd project
-- dir. The true cwd (needed to load) lives in the message lines. We label from
-- the generated title cache, falling back to the session's native `aiTitle`
scanners.claude_code = function()
    local entries = {}
    local titles = load_title_cache()
    local files =
        vim.fn.glob(vim.fn.expand('~/.claude/projects') .. '/*/*.jsonl', true, true)
    for _, file in ipairs(files) do
        local cwd, ai_title
        for _, d in ipairs(read_jsonl(file, 500)) do
            cwd = cwd or d.cwd
            ai_title = d.aiTitle or ai_title
        end
        if cwd then
            local session_id = vim.fn.fnamemodify(file, ':t:r')
            local cached = titles['claude_code:' .. session_id]
            entries[#entries + 1] = {
                adapter = 'claude_code',
                session_id = session_id,
                cwd = cwd,
                title = clean_title((cached and cached.title) or ai_title),
                updated_at = mtime(file),
                size = (vim.uv.fs_stat(file) or {}).size or 0,
                path = file,
            }
        end
    end
    return entries
end

-- Codex stores date-bucketed rollout-*.jsonl files. The first `session_meta`
-- line holds the id/cwd/timestamp; the label comes from the title cache
scanners.codex = function()
    local entries = {}
    local titles = load_title_cache()
    local files = vim.fn.glob(
        vim.fn.expand('~/.codex/sessions') .. '/**/rollout-*.jsonl',
        true,
        true
    )
    for _, file in ipairs(files) do
        local meta
        for _, d in ipairs(read_jsonl(file, 50)) do
            if d.type == 'session_meta' then
                meta = d.payload
                break
            end
        end
        if meta and meta.id and meta.cwd then
            local cached = titles['codex:' .. meta.id]
            entries[#entries + 1] = {
                adapter = 'codex',
                session_id = meta.id,
                cwd = meta.cwd,
                title = clean_title(cached and cached.title),
                updated_at = (
                    meta.timestamp and utils.timestamp_from_iso(meta.timestamp)
                ) or mtime(file),
                size = (vim.uv.fs_stat(file) or {}).size or 0,
                path = file,
            }
        end
    end
    return entries
end

-- Bring up the ACP connection. Only needed to load a session (listing reads
-- disk), so we defer it until after a pick to keep the picker instant and avoid
-- racing the connection setup against the picker opening
local function ensure_connection(chat)
    local handler = require('codecompanion.interactions.chat.acp.handler').new(chat)
    if not handler:ensure_connection() then
        utils.notify('No ACP connection available', vim.log.levels.WARN)
        return false
    end

    if not chat.acp_connection:can_load_session() then
        utils.notify(
            'This ACP adapter does not support loading sessions',
            vim.log.levels.WARN
        )
        return false
    end

    return true
end

-- Telescope display: <icon> <title> (~weight)  <clock> <time>  <cwd>
local function display_entry(picker_entry)
    local e = picker_entry.value
    local icon = e.display_icon or state_helpers.provider_icon(e.adapter)
    local title = pad_right(
        e.display_title or trim_chars(e.title or e.session_id, TITLE_WIDTH),
        e.display_title_width or 0
    )
    local weight = e.display_weight or fmt_weight(e.size)
    local weight_pad = string.rep(
        ' ',
        math.max((e.display_weight_width or 0) - vim.fn.strdisplaywidth(weight), 0)
    )
    local time = pad_right(
        e.display_time or (e.updated_at and utils.make_relative(e.updated_at) or '?'),
        e.display_time_width or 0
    )
    local cwd = e.display_cwd or (e.cwd and vim.fn.fnamemodify(e.cwd, ':~') or '')
    local clock = '\239\128\151' -- nf-fa-clock_o (U+F017)
    local meta = string.format('(%s)%s   %s %s', weight, weight_pad, clock, time)
    local line = string.format('%s %s  %s  %s', icon, title, meta, cwd)

    local title_end = #icon + 1 + #title
    return line, {
        { { title_end + 1, #line }, 'Comment' },
    }
end

local function load_entry(chat, entry)
    if not ensure_connection(chat) then
        return
    end

    -- The agent locates and roots the session by the cwd passed to session/load,
    -- so switch to the session's original cwd for the duration of the load
    local previous_cwd = vim.fn.getcwd()
    if entry.cwd and vim.fn.isdirectory(entry.cwd) == 1 then
        vim.api.nvim_set_current_dir(entry.cwd)
    end

    local updates = {}
    local ok = chat.acp_connection:load_session(entry.session_id, {
        on_session_update = function(update)
            table.insert(updates, update)
        end,
    })

    if vim.fn.getcwd() ~= previous_cwd and vim.fn.isdirectory(previous_cwd) == 1 then
        vim.api.nvim_set_current_dir(previous_cwd)
    end

    if not ok then
        return utils.notify('Failed to load ACP session', vim.log.levels.ERROR)
    end

    require('codecompanion.interactions.chat.acp.commands').link_buffer_to_session(
        chat.bufnr,
        chat.acp_connection.session_id
    )
    require('codecompanion.interactions.chat.acp.render').restore_session(chat, updates)

    if entry.title then
        chat:set_title(entry.title)
    end

    utils.fire('ACPChatRestored', {
        bufnr = chat.bufnr,
        id = chat.id,
        session_id = chat.acp_connection.session_id,
        title = chat.title,
    })
end

function M.browse(chat)
    if not chat or not chat.adapter or chat.adapter.type ~= 'acp' then
        return utils.notify(
            'ACP sessions require an ACP chat adapter',
            vim.log.levels.WARN
        )
    end

    if chat.cycle > 1 then
        return utils.notify(
            'ACP sessions must be loaded before submitting messages',
            vim.log.levels.WARN
        )
    end

    local scan = scanners[chat.adapter.name]
    if not scan then
        return utils.notify(
            'No session scanner for adapter: ' .. chat.adapter.name,
            vim.log.levels.WARN
        )
    end

    ensure_periodic_prune()

    local entries = scan()
    table.sort(entries, function(a, b)
        return (a.updated_at or 0) > (b.updated_at or 0)
    end)
    prepare_display(entries)

    if #entries == 0 then
        return utils.notify('No ACP sessions found', vim.log.levels.INFO)
    end

    -- Telescope picker so we can attach a delete action; <CR> resumes,
    -- d/<A-d> deletes the selected session and refreshes the list
    local pickers = require('telescope.pickers')
    local finders = require('telescope.finders')
    local conf = require('telescope.config').values
    local actions = require('telescope.actions')
    local action_state = require('telescope.actions.state')

    local function make_finder()
        return finders.new_table({
            results = entries,
            entry_maker = function(e)
                return {
                    value = e,
                    display = display_entry,
                    ordinal = (e.title or '') .. ' ' .. (e.cwd or ''),
                }
            end,
        })
    end

    -- Forward-declared so the attach_mappings and refresh closures below can
    -- reference the picker handle (not in scope inside its own initializer)
    local picker
    local provider = chat.adapter.name == 'claude_code' and 'Claude' or 'Codex'
    picker = pickers.new({}, {
        prompt_title = string.format('%s Sessions (<A-d>:delete)', provider),
        finder = make_finder(),
        sorter = conf.generic_sorter({}),
        attach_mappings = function(prompt_bufnr, map)
            local selection_hl =
                vim.api.nvim_get_hl(0, { name = 'TelescopeSelection', link = false })
            selection_hl.bold = true
            vim.api.nvim_set_hl(0, 'CodeCompanionSessionSelection', selection_hl)
            vim.wo[picker.results_win].winhighlight = table.concat(
                vim.tbl_filter(function(part)
                    return part ~= ''
                end, {
                    vim.wo[picker.results_win].winhighlight,
                    'TelescopeSelection:CodeCompanionSessionSelection',
                }),
                ','
            )

            actions.select_default:replace(function()
                local sel = action_state.get_selected_entry()
                actions.close(prompt_bufnr)
                if sel then
                    load_entry(chat, sel.value)
                end
            end)

            local function delete()
                local sel = action_state.get_selected_entry()
                if not sel then
                    return
                end
                local e = sel.value
                if not delete_session(e.path) then
                    return utils.notify('Failed to delete session', vim.log.levels.ERROR)
                end
                for i = #entries, 1, -1 do
                    if entries[i] == e then
                        table.remove(entries, i)
                    end
                end
                picker:refresh(make_finder(), { reset_prompt = false })
                utils.notify(
                    'Deleted session: ' .. (e.title or e.session_id),
                    vim.log.levels.INFO
                )
            end

            map('n', 'd', delete)
            map('i', '<A-d>', delete)
            return true
        end,
    })
    picker:find()

    -- Refresh titles for changed sessions in the background so the picker opens
    -- instantly, then patch the open picker in place if any title actually moved
    vim.system({ 'ai_session_title' }, { text = true }, function(obj)
        if tonumber((obj.stdout or ''):match('generated (%d+)')) == 0 then
            return
        end
        vim.schedule(function()
            if
                not picker.prompt_bufnr
                or not vim.api.nvim_buf_is_valid(picker.prompt_bufnr)
            then
                return
            end
            local titles = load_title_cache()
            for _, e in ipairs(entries) do
                local cached = titles[e.adapter .. ':' .. e.session_id]
                if cached and cached.title then
                    e.title = clean_title(cached.title)
                end
            end
            prepare_display(entries)
            pcall(function()
                picker:refresh(make_finder(), { reset_prompt = false })
            end)
        end)
    end)
end

return M
