[tool.ruff]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "B", # Bugbear plugin
    "D"  # pydocstyle plugin
    ]

ignore = [
    "E203", # Whitespace before ':'
    "E402", # Import not at top of file
    "E501", # Line too long
    "B006", # Mutable data structures in argument defaults
    "D107", # Missing docstring in init
    "D203", # Same as D211 about class docstring
    "D213", # Same as D212 about summary docstring
    ]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = []
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

line-length = 88  # Same as Black.

[tool.ruff.per-file-ignores]
# Don't ask for docstring in test files
"test_*.py" = ["D100", "D101", "D102", "D102", "D103"]
