[tool.ruff]
line-length = 88
extend-include = ["*.ipynb"]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "B", # Bugbear plugin
    "D", # pydocstyle plugin
    "I", # isort
]

ignore = [
    "E203", # Whitespace before ':'
    "E402", # Import not at top of file
    "E501", # Line too long
    "B006", # Mutable data structures in argument defaults
    "D107", # Missing docstring in init
    "D203", # Same as D211 about class docstring
    "D213", # Same as D212 about summary docstring
    "D413", # Missing blank linke after last section
]

# Rules eligible for autofix
fixable = ["I"]

# Exclude a variety of commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint.per-file-ignores]
# Don't ask for docstring in test files
"test_*.py" = ["D100", "D101", "D102", "D102", "D103"]

[tool.ruff.lint.pydocstyle]
convention = "google"
