#!/bin/bash

setxkbmap -layout us,es -option grp:win_space_toggle -option ctrl:nocaps
# Map < (next to z) to ` and change spanish tilde position (next to p)
xmodmap -e "keycode 94 = grave asciitilde"
xmodmap -e "keycode  34 = bracketleft braceleft dead_acute dead_circumflex bracketleft dead_abovering"
xbacklight -set 50
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

[[ -f ~/.fehbg ]] && ~/.fehbg &
dunst &
onedrive --synchronize --monitor &
udiskie &
compton -cCG -r 7 &
xfce4-power-manager &
dual init
exec i3
