#!/bin/bash

setxkbmap -layout us,es -option grp:win_space_toggle -option ctrl:nocaps
# Map the key next to z (<) to tilde (use `xev` to find the actual keycode)
xmodmap -e "keycode 94 = grave asciitilde"
xbacklight -set 50
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

[[ -f ~/.fehbg ]] && ~/.fehbg &
dunst &
onedrive --synchronize --monitor &
udiskie &
compton -cCG -r 7 &
[[ -f ~/bin/dual ]] && ~/bin/dual init
exec i3
