[package]
name = "latex-article"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Pedro"]
description = "Classic LaTeX-style articles."
compiler = "0.15.0"

[template]
path = "template"
entrypoint = "main.typ"
