#!/bin/bash

# X stuff
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
setxkbmap -layout us,es -option grp:win_space_toggle -option ctrl:nocaps
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
xbacklight -set 30

# Programs
unclutter --timeout 2 &
dunst &
udiskie &
picom &
xfce4-power-manager &
multimon init
exec i3
