#!/bin/bash

# X stuff
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
setxkbmap -layout us,es -option grp:win_space_toggle -option ctrl:nocaps
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
xbacklight -set 35

# Programs
unclutter &
dunst &
udiskie &
compton -cCG -r 7 &
xfce4-power-manager &
multimon init
exec i3
