#!/bin/bash

# X stuff
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
setxkbmap -layout us,es -option grp:win_space_toggle -option ctrl:nocaps
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
xbacklight -set "$LAPTOP_XBRIGHTNESS"

# Ensure xinitrc.d scripts are sourced (and a session starts correctly)
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Programs
unclutter --timeout 1 &
dunst &
udiskie &
picom &
xfce4-power-manager &
multimon init
nohup soupawhisper > /tmp/soupawhisper.log 2>&1 < /dev/null &
exec i3
