---
# The parser expects this file to be indented with 2 spaces
config:
  fallback-icon: ''
  icon-position: 'right'
  show-name: true

icons:
  claude: ''
  codex: ''
  ctop: '󰡨'
  nvim: ''
  python3: ''
  python: ''
